#!/bin/sh

#-hda build/image.img \

qemu-system-i386 -debugcon stdio \
                        -drive if=none,id=stick,format=raw,file=build/image.img \
                        -device piix3-usb-uhci,id=uhci                              \
                        -device usb-storage,bus=uhci.0,drive=stick
