#!/bin/sh

#-hda build/image.img \

qemu-system-i386 -debugcon stdio \
                        -drive if=none,id=stick,format=raw,file=build/image.img \
                        -device usb-ehci,id=ehci                              \
                        -device usb-storage,bus=ehci.0,drive=stick
