#pragma once

// panic error codes
#define PANIC_OK ((u32)0x00)

#define KERNEL_PANIC_BASE        ((u32)0x800)
#define PANIC_CLASS_GENERIC      (KERNEL_PANIC_BASE | 0x00)
#define PANIC_UNEXPECTED_FAILURE (PANIC_CLASS_GENERIC | 0x01)

#define PANIC_CLASS_MEMORY       (KERNEL_PANIC_BASE | 0x10)
#define PANIC_BAD_MEMORY_REQUEST (PANIC_CLASS_MEMORY | 0x01)
#define PANIC_OBJ_POOL_FULL      (PANIC_CLASS_MEMORY | 0x02)
